baseurl: /
languageCode: en-us
author:
    name: Milan Valášek
title: Research Skills for IUDD
googleAnalytics: ""
disqusShortname: "mival"
ignoreFiles:
    - \.Rmd$
    - \.Rmarkdown$
    - _cache$
    - \.knit\.md$
    - \.utf8\.md$
    - \.qmd$
    - \.ipynb$
relativeURLS: false
params:
    hostedOn: "https://iudd-research.netlify.app"
    blogReadSpeed: 220
permalinks:
    blog: /blog/:year/:month/:slug/
menu:
    main:
        - identifier: Welcome
          weight: 1
          url: /
enableInlineShortcodes: true
enableEmoji: true
markup:
    defaultMarkdownHandler: goldmark
    goldmark:
        renderer:
            unsafe: true
        parser:
            attribute:
                block: true
    highlight:
        style: pygments
        noClasses: false
summaryLength: 200
security:
    exec:
        allow:
            ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^pandoc$"]
buildFuture: true