---
title: Introduction to Research Skills
date: "2023-10-08"
format: hugo-md
type: revealjs
execute:
  echo: false
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(dev.args = list(bg="transparent"))

```

## Welcome

- something

**bold**

[some link](https://www.google.com)

```{r}
#| echo: false
#| results: 'asis'
wrap = function(x="", tag="div", class, attr, close=TRUE) {
    orig_tag = tag
    if (!missing(class)) {
        tag = paste0(tag, ' class="', class, '"')
    }
    if (!missing(attr)) {
        tag = paste(tag, attr)
    }
    out = paste0("<", tag, ">", x)
    if (close) {out = paste0(out, "</", orig_tag, ">")} 
    return(out)
}

make_title = function(title, include_title=FALSE) {
    paste(
        ifelse(include_title,
            paste0('<h2 class="hidden" auto-animate="true" auto-animate-easing="ease-in-out">', title, '</h2>'),
            '<h2 class="hidden" auto-animate="true" auto-animate-easing="ease-in-out"></h2>'
            ),
        wrap(title, class="animate-title", attr='data-id="animate-title"'),
        wrap(class="timeline", close=FALSE),
        wrap(class="line", attr='data-id="line"'),
        sep='\n')
}

make_timeline = function(title, content) {

    formatted_content = list()
    for (i in 1:length(content)) {
        formatted_content[[i]] = wrap(
            paste0(
                wrap(content[[i]]$when, class="when"),
                "\n",
                wrap(content[[i]]$what, class="what"),
                "\n",
                wrap(content[[i]]$where, class="where")
            ),
            tag="li", attr=paste0('data-id="p', i, '"')
        )
    }

    out = ""
    for (i in 1:length(formatted_content)) {
        out = paste0(
            out,
            make_title(title, i==1),
            wrap(paste(formatted_content[1:i], collapse = ""), tag="ul"),
            "</alt-div>",
            sep = "\n")
    }
    cat("```{=html}\n", out, "\n```")
}

cv = list(
    list(
        what="PhD Psychology",
        where="University of Edinburgh",
        when="2011-2015"
    ),
    list(
        what="Psychometrics",
        where="Royal College of Surgeons of Edinburgh",
        when="2015-2017"
    ),
    list(
        what="Teacher/Lecturer in research methods & statistics",
        where="Universities of Edinburgh and Sussex",
        when="2017-2022"
    ),
    list(
        what="Research associate",
        where="InfAR @ Bauhaus",
        when="2022-present"
    )
)

make_timeline("Who am I?", cv)
```


## scatter

```{r}
library(ggplot2)
main_col = "#1860ac"
update_geom_defaults("point", list(colour = main_col, size = 3))
update_geom_defaults("bar", list(colour = main_col, fill = paste0(main_col, "aa")))
my_theme <- theme(
        line = element_line(colour = main_col),
        text = element_text(colour = main_col),
        plot.background = element_blank(),
        panel.background = element_rect(
            fill = "white",
            colour = main_col),
        panel.grid.major = element_line(colour = paste0(main_col, "30")),
        panel.grid.minor = element_line(colour = paste0(main_col, "25")),
        axis.ticks = element_line(colour = "white"),
        axis.text = element_text(colour = "white", size = 12),
        axis.title = element_text(colour = "white", size = 18),
        axis.title.x.bottom = element_text(vjust=-0.5)
    )
df <- tibble::tibble(x = rnorm(100), y = x + rnorm(100))
df |>
    ggplot(aes(x, y)) +
    geom_point() +
    labs(x = "blah", y = "blee") +
    my_theme
```

## Hist

```{r}
df |>
    ggplot(aes(x)) + geom_histogram() + my_theme
```
